### ISSUE TITLE
`LBtcSwapScriptV2::get_balance()` results in error

### ISSUE THREAD

**Issue by ok300** [SatoshiPortal/boltz-rust#48]
Calling

https://github.com/SatoshiPortal/boltz-rust/blob/8c92a59e1c555616844d5acd7d3231a3119549bf/src/swaps/liquidv2.rs#L321

results in an error of type

```
Electrum(AllAttemptsErrored([SharedIOError(Kind(UnexpectedEof))])
```

**Comment by i5hi** [comment]
hey! yes, this is a known issue where electrum-rs doesnt' directly support all methods. 

I would suggest not using get_balance and just use fetch_utxos instead. If you need balance, you can compute it from the utxos.

**Comment by i5hi** [comment]
even with fetch utxos, you will notice we cannot use the `list_unspent` method, instead we use `script_get_history`

**Comment by ok300** [comment]
Interesting, thanks!

As a workaround, would it make sense to remove or deprecate `LBtcSwapScriptV2::get_balance()`? I'm thinking others could fall into the same trap.

**Comment by i5hi** [comment]
Yes. I will remove it.

**Comment by i5hi** [comment]
Thanks!
