### ISSUE TITLE
Place `lnurl-rs` behind feature flag

### ISSUE THREAD

**Issue by ok300** [SatoshiPortal/boltz-rust#80]
Please place the `lnurl-rs` dependency behind a feature flag.

Some callers may want to exclude it, since it brings quite a lot of dependencies[^1] and they may have already implemented LNURL support separately.

[^1]: https://crates.io/crates/lnurl-rs/0.8.0/dependencies

**Comment by i5hi** [comment]
https://github.com/SatoshiPortal/boltz-rust/commit/c3aee9fd9e4e2d3b7d83107841d2e29d088d84e1

**Comment by ok300** [comment]
Thanks, works!
